%------------------------------------------------------------------------------
% File     : CSR027-10 : TPTP v9.2.1. Released v7.3.0.
% Domain   : Puzzles
% Problem  : Autogenerated Cyc Problem CSR027+1
% Version  : Especial.
% English  :

% Refs     : [CS18]  Claessen & Smallbone (2018), Efficient Encodings of Fi
%          : [Sma18] Smallbone (2018), Email to Geoff Sutcliffe
% Source   : [Sma18]
% Names    :

% Status   : Unsatisfiable
% Rating   : 0.17 v9.1.0, 0.23 v8.2.0, 0.25 v8.1.0, 0.10 v7.5.0, 0.25 v7.4.0, 0.26 v7.3.0
% Syntax   : Number of clauses     :   85 (  85 unt;   0 nHn;  17 RR)
%            Number of literals    :   85 (  85 equ;   1 neg)
%            Maximal clause size   :    1 (   1 avg)
%            Maximal term depth    :    6 (   1 avg)
%            Number of predicates  :    1 (   0 usr;   0 prp; 2-2 aty)
%            Number of functors    :   60 (  60 usr;  26 con; 0-4 aty)
%            Number of variables   :  155 (  63 sgn)
% SPC      : CNF_UNS_RFO_PEQ_UEQ

% Comments : Converted from CSR027+1 to UEQ using [CS18].
%------------------------------------------------------------------------------
cnf(ifeq_axiom,axiom,
    ifeq3(A,A,B,C) = B ).

cnf(ifeq_axiom_001,axiom,
    ifeq2(A,A,B,C) = B ).

cnf(ifeq_axiom_002,axiom,
    ifeq(A,A,B,C) = B ).

cnf(just1,axiom,
    ifeq3(relationallexists(PRED,INDEPCOL,DEPCOL),true,ifeq3(isa(TERM,INDEPCOL),true,isa(f_relationallexistsfn(TERM,PRED,INDEPCOL,DEPCOL),DEPCOL),true),true) = true ).

cnf(just2,axiom,
    resultisaarg(c_relationallexistsfn,n_4) = true ).

cnf(just3,axiom,
    genlmt(c_calendarsmt,c_calendarsvocabularymt) = true ).

cnf(just4,axiom,
    transitivebinarypredicate(c_genlmt) = true ).

cnf(just5,axiom,
    genlmt(c_basekb,c_universalvocabularymt) = true ).

cnf(just6,axiom,
    genlmt(c_cyclistsmt,c_calendarsmt) = true ).

cnf(just7,axiom,
    genlmt(c_calendarsvocabularymt,c_basekb) = true ).

cnf(just8,axiom,
    genlmt(c_tptp_spindleheadmt,c_cyclistsmt) = true ).

cnf(just9,axiom,
    genlmt(c_tptp_spindlecollectormt,c_tptp_member2610_mt) = true ).

cnf(just10,axiom,
    genlmt(c_tptp_member3993_mt,c_tptp_spindleheadmt) = true ).

cnf(just11,axiom,
    genlmt(c_tptp_spindlecollectormt,c_tptp_member3993_mt) = true ).

cnf(just12,axiom,
    ifeq3(mtvisible(c_tptp_member2610_mt),true,ifeq3(isa(TERM,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)),true,tptp_8_875(TERM,f_relationallexistsfn(TERM,c_tptp_8_875,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent),c_tptpcol_16_31868)),true),true) = true ).

cnf(just13,axiom,
    ifeq3(mtvisible(c_tptp_member2610_mt),true,relationallexists(c_tptp_8_875,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent),c_tptpcol_16_31868),true) = true ).

cnf(just14,axiom,
    isa(c_tptpnsubcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent_786,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)) = true ).

cnf(just15,axiom,
    subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(c_tptpnsubcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent_786) = true ).

cnf(just17,axiom,
    ifeq3(genlinverse(PRED,GENLPRED),true,ifeq3(genlinverse(SPECPRED,PRED),true,genlpreds(SPECPRED,GENLPRED),true),true) = true ).

cnf(just18,axiom,
    ifeq3(genlpreds(ARG1,INS),true,predicate(INS),true) = true ).

cnf(just19,axiom,
    ifeq3(genlpreds(ARG1,INS),true,predicate(INS),true) = true ).

cnf(just20,axiom,
    ifeq3(genlpreds(INS,ARG2),true,predicate(INS),true) = true ).

cnf(just21,axiom,
    ifeq3(genlpreds(INS,ARG2),true,predicate(INS),true) = true ).

cnf(just22,axiom,
    ifeq3(genlpreds(Y,Z),true,ifeq3(genlpreds(X,Y),true,genlpreds(X,Z),true),true) = true ).

cnf(just23,axiom,
    ifeq3(predicate(X),true,genlpreds(X,X),true) = true ).

cnf(just24,axiom,
    ifeq3(predicate(X),true,genlpreds(X,X),true) = true ).

cnf(just25,axiom,
    ifeq3(genlinverse(ARG1,INS),true,binarypredicate(INS),true) = true ).

cnf(just26,axiom,
    ifeq3(genlinverse(INS,ARG2),true,binarypredicate(INS),true) = true ).

cnf(just27,axiom,
    ifeq3(genlpreds(NEW,OLD),true,ifeq3(genlinverse(OLD,ARG2),true,genlinverse(NEW,ARG2),true),true) = true ).

cnf(just28,axiom,
    ifeq3(genlpreds(OLD,NEW),true,ifeq3(genlinverse(ARG1,OLD),true,genlinverse(ARG1,NEW),true),true) = true ).

cnf(just29,axiom,
    ifeq3(disjointwith(ARG1,INS),true,collection(INS),true) = true ).

cnf(just30,axiom,
    ifeq3(disjointwith(INS,ARG2),true,collection(INS),true) = true ).

cnf(just31,axiom,
    ifeq3(disjointwith(X,Y),true,disjointwith(Y,X),true) = true ).

cnf(just32,axiom,
    ifeq3(genls(NEW,OLD),true,ifeq3(disjointwith(ARG1,OLD),true,disjointwith(ARG1,NEW),true),true) = true ).

cnf(just33,axiom,
    ifeq3(genls(NEW,OLD),true,ifeq3(disjointwith(OLD,ARG2),true,disjointwith(NEW,ARG2),true),true) = true ).

cnf(just34,axiom,
    ifeq3(isa(X,c_tptpcol_16_31868),true,tptpcol_16_31868(X),true) = true ).

cnf(just35,axiom,
    ifeq3(tptpcol_16_31868(X),true,isa(X,c_tptpcol_16_31868),true) = true ).

cnf(just36,axiom,
    ifeq3(isa(X,c_movement_translationevent),true,movement_translationevent(X),true) = true ).

cnf(just37,axiom,
    ifeq3(movement_translationevent(X),true,isa(X,c_movement_translationevent),true) = true ).

cnf(just38,axiom,
    ifeq3(directionoftranslation_throughout(ARG1,INS),true,unitvectorinterval(INS),true) = true ).

cnf(just39,axiom,
    ifeq3(directionoftranslation_throughout(INS,ARG2),true,movement_translationevent(INS),true) = true ).

cnf(just40,axiom,
    ifeq3(subevents(OLD,NEW),true,ifeq3(directionoftranslation_throughout(OLD,ARG2),true,directionoftranslation_throughout(NEW,ARG2),true),true) = true ).

cnf(just41,axiom,
    ifeq3(isa(X,c_unitvectorinterval),true,unitvectorinterval(X),true) = true ).

cnf(just42,axiom,
    ifeq3(unitvectorinterval(X),true,isa(X,c_unitvectorinterval),true) = true ).

cnf(just43,axiom,
    natfunction(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),c_subcollectionofwithrelationfromtypefn) = true ).

cnf(just44,axiom,
    natargument(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),n_1,ARG1) = true ).

cnf(just45,axiom,
    natargument(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),n_2,ARG2) = true ).

cnf(just46,axiom,
    natargument(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3),n_3,ARG3) = true ).

cnf(just47,axiom,
    collection(f_subcollectionofwithrelationfromtypefn(ARG1,ARG2,ARG3)) = true ).

cnf(just48,axiom,
    ifeq3(isa(X,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)),true,subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(X),true) = true ).

cnf(just49,axiom,
    ifeq3(subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(X),true,isa(X,f_subcollectionofwithrelationfromtypefn(c_unitvectorinterval,c_directionoftranslation_throughout,c_movement_translationevent)),true) = true ).

cnf(just50,axiom,
    ifeq3(tptp_8_875(ARG1,INS),true,tptpcol_4_24578(INS),true) = true ).

cnf(just51,axiom,
    ifeq3(tptp_8_875(INS,ARG2),true,subcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent(INS),true) = true ).

cnf(just52,axiom,
    ifeq3(relationallexists(ARG1,ARG2,INS),true,collection(INS),true) = true ).

cnf(just53,axiom,
    ifeq3(relationallexists(ARG1,INS,ARG3),true,collection(INS),true) = true ).

cnf(just54,axiom,
    ifeq3(relationallexists(INS,ARG2,ARG3),true,binarypredicate(INS),true) = true ).

cnf(just55,axiom,
    mtvisible(c_basekb) = true ).

cnf(just56,axiom,
    ifeq3(isa(X,c_transitivebinarypredicate),true,transitivebinarypredicate(X),true) = true ).

cnf(just57,axiom,
    ifeq3(transitivebinarypredicate(X),true,isa(X,c_transitivebinarypredicate),true) = true ).

cnf(just58,axiom,
    ifeq3(isa(ARG1,INS),true,collection(INS),true) = true ).

cnf(just59,axiom,
    ifeq3(isa(ARG1,INS),true,collection(INS),true) = true ).

cnf(just60,axiom,
    ifeq3(isa(INS,ARG2),true,thing(INS),true) = true ).

cnf(just61,axiom,
    ifeq3(isa(INS,ARG2),true,thing(INS),true) = true ).

cnf(just62,axiom,
    ifeq3(genls(OLD,NEW),true,ifeq3(isa(ARG1,OLD),true,isa(ARG1,NEW),true),true) = true ).

cnf(just63,axiom,
    ifeq3(genlmt(SPECMT,GENLMT),true,ifeq3(mtvisible(SPECMT),true,mtvisible(GENLMT),true),true) = true ).

cnf(just64,axiom,
    ifeq3(genlmt(ARG1,INS),true,microtheory(INS),true) = true ).

cnf(just65,axiom,
    ifeq3(genlmt(ARG1,INS),true,microtheory(INS),true) = true ).

cnf(just66,axiom,
    ifeq3(genlmt(INS,ARG2),true,microtheory(INS),true) = true ).

cnf(just67,axiom,
    ifeq3(genlmt(INS,ARG2),true,microtheory(INS),true) = true ).

cnf(just68,axiom,
    ifeq3(genlmt(Y,Z),true,ifeq3(genlmt(X,Y),true,genlmt(X,Z),true),true) = true ).

cnf(just69,axiom,
    ifeq3(microtheory(X),true,genlmt(X,X),true) = true ).

cnf(just70,axiom,
    ifeq3(microtheory(X),true,genlmt(X,X),true) = true ).

cnf(just71,axiom,
    natfunction(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),c_relationallexistsfn) = true ).

cnf(just72,axiom,
    natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_1,ARG1) = true ).

cnf(just73,axiom,
    natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_2,ARG2) = true ).

cnf(just74,axiom,
    natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_3,ARG3) = true ).

cnf(just75,axiom,
    natargument(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4),n_4,ARG4) = true ).

cnf(just76,axiom,
    thing(f_relationallexistsfn(ARG1,ARG2,ARG3,ARG4)) = true ).

cnf(just77,axiom,
    ifeq3(resultisaarg(ARG1,INS),true,positiveinteger(INS),true) = true ).

cnf(just78,axiom,
    ifeq3(resultisaarg(INS,ARG2),true,function_denotational(INS),true) = true ).

cnf(just79,axiom,
    mtvisible(c_universalvocabularymt) = true ).

cnf(query27,negated_conjecture,
    mtvisible(c_tptp_spindlecollectormt) = true ).

cnf(just16,axiom,
    ifeq(tuple(isa(OBJ,COL1),isa(OBJ,COL2),disjointwith(COL1,COL2)),tuple(true,true,true),a,b) = b ).

cnf(query27_1,negated_conjecture,
    ifeq2(tuple2(tptp_8_875(c_tptpnsubcollectionofwithrelationfromtypefnunitvectorintervaldirectionoftranslation_throughoutmovement_translationevent_786,X),tptpcol_16_31868(X)),tuple2(true,true),a,b) = b ).

cnf(goal,negated_conjecture,
    a != b ).

%------------------------------------------------------------------------------
