%------------------------------------------------------------------------------
% File     : CSR041-10 : TPTP v9.2.1. Released v7.5.0.
% Domain   : Puzzles
% Problem  : Autogenerated Cyc Problem CSR041+1
% Version  : Especial.
% English  :

% Refs     : [CS18]  Claessen & Smallbone (2018), Efficient Encodings of Fi
%          : [Sma18] Smallbone (2018), Email to Geoff Sutcliffe
% Source   : [Sma18]
% Names    :

% Status   : Unsatisfiable
% Rating   : 0.09 v8.2.0, 0.12 v8.1.0, 0.05 v7.5.0
% Syntax   : Number of clauses     :   78 (  78 unt;   0 nHn;  15 RR)
%            Number of literals    :   78 (  78 equ;   1 neg)
%            Maximal clause size   :    1 (   1 avg)
%            Maximal term depth    :    6 (   1 avg)
%            Number of predicates  :    1 (   0 usr;   0 prp; 2-2 aty)
%            Number of functors    :   48 (  48 usr;  22 con; 0-4 aty)
%            Number of variables   :  119 (  33 sgn)
% SPC      : CNF_UNS_RFO_PEQ_UEQ

% Comments : Converted from CSR041+1 to UEQ using [CS18].
%------------------------------------------------------------------------------
cnf(ifeq_axiom,axiom,
    ifeq3(A,A,B,C) = B ).

cnf(ifeq_axiom_001,axiom,
    ifeq2(A,A,B,C) = B ).

cnf(ifeq_axiom_002,axiom,
    ifeq(A,A,B,C) = B ).

cnf(just1,axiom,
    genls(c_aspatialinformationstore,c_aspatialthing) = true ).

cnf(just2,axiom,
    ifeq3(aspatialinformationstore(OBJ),true,aspatialthing(OBJ),true) = true ).

cnf(just3,axiom,
    genls(c_microtheory,c_aspatialinformationstore) = true ).

cnf(just4,axiom,
    ifeq3(microtheory(OBJ),true,aspatialinformationstore(OBJ),true) = true ).

cnf(just5,axiom,
    genlmt(c_calendarsmt,c_calendarsvocabularymt) = true ).

cnf(just6,axiom,
    transitivebinarypredicate(c_genlmt) = true ).

cnf(just7,axiom,
    microtheory(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_wwwinformationblastcomtechnical_university_of_munichhtml)),c_translation_3)) = true ).

cnf(just8,axiom,
    genlmt(c_basekb,c_universalvocabularymt) = true ).

cnf(just9,axiom,
    genlmt(c_cyclistsmt,c_calendarsmt) = true ).

cnf(just10,axiom,
    genlmt(c_calendarsvocabularymt,c_basekb) = true ).

cnf(just11,axiom,
    genlmt(c_tptp_spindleheadmt,c_cyclistsmt) = true ).

cnf(just12,axiom,
    genlmt(c_tptp_member2831_mt,c_tptp_spindleheadmt) = true ).

cnf(just14,axiom,
    ifeq3(genlinverse(PRED,GENLPRED),true,ifeq3(genlinverse(SPECPRED,PRED),true,genlpreds(SPECPRED,GENLPRED),true),true) = true ).

cnf(just15,axiom,
    ifeq3(genlpreds(ARG1,INS),true,predicate(INS),true) = true ).

cnf(just16,axiom,
    ifeq3(genlpreds(ARG1,INS),true,predicate(INS),true) = true ).

cnf(just17,axiom,
    ifeq3(genlpreds(INS,ARG2),true,predicate(INS),true) = true ).

cnf(just18,axiom,
    ifeq3(genlpreds(INS,ARG2),true,predicate(INS),true) = true ).

cnf(just19,axiom,
    ifeq3(genlpreds(Y,Z),true,ifeq3(genlpreds(X,Y),true,genlpreds(X,Z),true),true) = true ).

cnf(just20,axiom,
    ifeq3(predicate(X),true,genlpreds(X,X),true) = true ).

cnf(just21,axiom,
    ifeq3(predicate(X),true,genlpreds(X,X),true) = true ).

cnf(just22,axiom,
    ifeq3(genlinverse(ARG1,INS),true,binarypredicate(INS),true) = true ).

cnf(just23,axiom,
    ifeq3(genlinverse(INS,ARG2),true,binarypredicate(INS),true) = true ).

cnf(just24,axiom,
    ifeq3(genlpreds(NEW,OLD),true,ifeq3(genlinverse(OLD,ARG2),true,genlinverse(NEW,ARG2),true),true) = true ).

cnf(just25,axiom,
    ifeq3(genlpreds(OLD,NEW),true,ifeq3(genlinverse(ARG1,OLD),true,genlinverse(ARG1,NEW),true),true) = true ).

cnf(just26,axiom,
    ifeq3(disjointwith(ARG1,INS),true,collection(INS),true) = true ).

cnf(just27,axiom,
    ifeq3(disjointwith(INS,ARG2),true,collection(INS),true) = true ).

cnf(just28,axiom,
    ifeq3(disjointwith(X,Y),true,disjointwith(Y,X),true) = true ).

cnf(just29,axiom,
    ifeq3(genls(NEW,OLD),true,ifeq3(disjointwith(ARG1,OLD),true,disjointwith(ARG1,NEW),true),true) = true ).

cnf(just30,axiom,
    ifeq3(genls(NEW,OLD),true,ifeq3(disjointwith(OLD,ARG2),true,disjointwith(NEW,ARG2),true),true) = true ).

cnf(just31,axiom,
    mtvisible(c_basekb) = true ).

cnf(just32,axiom,
    natfunction(f_urlfn(ARG1),c_urlfn) = true ).

cnf(just33,axiom,
    natargument(f_urlfn(ARG1),n_1,ARG1) = true ).

cnf(just34,axiom,
    uniformresourcelocator(f_urlfn(ARG1)) = true ).

cnf(just35,axiom,
    natfunction(f_urlreferentfn(ARG1),c_urlreferentfn) = true ).

cnf(just36,axiom,
    natargument(f_urlreferentfn(ARG1),n_1,ARG1) = true ).

cnf(just37,axiom,
    computerdataartifact(f_urlreferentfn(ARG1)) = true ).

cnf(just38,axiom,
    natfunction(f_contentmtofcdafromeventfn(ARG1,ARG2),c_contentmtofcdafromeventfn) = true ).

cnf(just39,axiom,
    natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_1,ARG1) = true ).

cnf(just40,axiom,
    natargument(f_contentmtofcdafromeventfn(ARG1,ARG2),n_2,ARG2) = true ).

cnf(just41,axiom,
    microtheory(f_contentmtofcdafromeventfn(ARG1,ARG2)) = true ).

cnf(just42,axiom,
    ifeq3(isa(X,c_transitivebinarypredicate),true,transitivebinarypredicate(X),true) = true ).

cnf(just43,axiom,
    ifeq3(transitivebinarypredicate(X),true,isa(X,c_transitivebinarypredicate),true) = true ).

cnf(just44,axiom,
    ifeq3(isa(ARG1,INS),true,collection(INS),true) = true ).

cnf(just45,axiom,
    ifeq3(isa(ARG1,INS),true,collection(INS),true) = true ).

cnf(just46,axiom,
    ifeq3(isa(INS,ARG2),true,thing(INS),true) = true ).

cnf(just47,axiom,
    ifeq3(isa(INS,ARG2),true,thing(INS),true) = true ).

cnf(just48,axiom,
    ifeq3(genls(OLD,NEW),true,ifeq3(isa(ARG1,OLD),true,isa(ARG1,NEW),true),true) = true ).

cnf(just49,axiom,
    ifeq3(mtvisible(SPECMT),true,ifeq3(genlmt(SPECMT,GENLMT),true,mtvisible(GENLMT),true),true) = true ).

cnf(just50,axiom,
    ifeq3(genlmt(ARG1,INS),true,microtheory(INS),true) = true ).

cnf(just51,axiom,
    ifeq3(genlmt(ARG1,INS),true,microtheory(INS),true) = true ).

cnf(just52,axiom,
    ifeq3(genlmt(INS,ARG2),true,microtheory(INS),true) = true ).

cnf(just53,axiom,
    ifeq3(genlmt(INS,ARG2),true,microtheory(INS),true) = true ).

cnf(just54,axiom,
    ifeq3(genlmt(Y,Z),true,ifeq3(genlmt(X,Y),true,genlmt(X,Z),true),true) = true ).

cnf(just55,axiom,
    ifeq3(microtheory(X),true,genlmt(X,X),true) = true ).

cnf(just56,axiom,
    ifeq3(microtheory(X),true,genlmt(X,X),true) = true ).

cnf(just57,axiom,
    ifeq3(isa(X,c_microtheory),true,microtheory(X),true) = true ).

cnf(just58,axiom,
    ifeq3(microtheory(X),true,isa(X,c_microtheory),true) = true ).

cnf(just59,axiom,
    ifeq3(isa(X,c_aspatialthing),true,aspatialthing(X),true) = true ).

cnf(just60,axiom,
    ifeq3(aspatialthing(X),true,isa(X,c_aspatialthing),true) = true ).

cnf(just61,axiom,
    ifeq3(isa(X,c_aspatialinformationstore),true,aspatialinformationstore(X),true) = true ).

cnf(just62,axiom,
    ifeq3(aspatialinformationstore(X),true,isa(X,c_aspatialinformationstore),true) = true ).

cnf(just63,axiom,
    ifeq3(genls(ARG1,INS),true,collection(INS),true) = true ).

cnf(just64,axiom,
    ifeq3(genls(ARG1,INS),true,collection(INS),true) = true ).

cnf(just65,axiom,
    ifeq3(genls(INS,ARG2),true,collection(INS),true) = true ).

cnf(just66,axiom,
    ifeq3(genls(INS,ARG2),true,collection(INS),true) = true ).

cnf(just67,axiom,
    ifeq3(genls(Y,Z),true,ifeq3(genls(X,Y),true,genls(X,Z),true),true) = true ).

cnf(just68,axiom,
    ifeq3(collection(X),true,genls(X,X),true) = true ).

cnf(just69,axiom,
    ifeq3(collection(X),true,genls(X,X),true) = true ).

cnf(just70,axiom,
    ifeq3(genls(NEW,OLD),true,ifeq3(genls(OLD,ARG2),true,genls(NEW,ARG2),true),true) = true ).

cnf(just71,axiom,
    ifeq3(genls(OLD,NEW),true,ifeq3(genls(ARG1,OLD),true,genls(ARG1,NEW),true),true) = true ).

cnf(just72,axiom,
    mtvisible(c_universalvocabularymt) = true ).

cnf(query41,negated_conjecture,
    mtvisible(c_tptp_member2831_mt) = true ).

cnf(just13,axiom,
    ifeq(tuple(isa(OBJ,COL1),isa(OBJ,COL2),disjointwith(COL1,COL2)),tuple(true,true,true),a,b) = b ).

cnf(query41_1,negated_conjecture,
    ifeq2(aspatialthing(f_contentmtofcdafromeventfn(f_urlreferentfn(f_urlfn(s_http_wwwinformationblastcomtechnical_university_of_munichhtml)),c_translation_3)),true,a,b) = b ).

cnf(goal,negated_conjecture,
    a != b ).

%------------------------------------------------------------------------------
