%--------------------------------------------------------------------------
% File     : NLP007-1 : TPTP v9.2.1. Released v2.4.0.
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem 7
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".

% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner (1999), FTP'2000 - Problem Sets
% Source   : [TPTP]
% Names    :

% Status   : Unsatisfiable
% Rating   : 0.00 v3.1.0, 0.11 v2.7.0, 0.17 v2.6.0, 0.11 v2.5.0, 0.00 v2.4.0
% Syntax   : Number of clauses     :   60 (  16 unt;  21 nHn;  60 RR)
%            Number of literals    :  160 (   4 equ;  80 neg)
%            Maximal clause size   :   30 (   2 avg)
%            Maximal term depth    :    1 (   1 avg)
%            Number of predicates  :   22 (  21 usr;   1 prp; 0-2 aty)
%            Number of functors    :   16 (  16 usr;  16 con; 0-0 aty)
%            Number of variables   :   16 (   0 sgn)
% SPC      : CNF_UNS_EPR_SEQ_NHN

% Comments : Created from NLP007+1.p using FLOTTER
%--------------------------------------------------------------------------
cnf(clause1,negated_conjecture,
    city(skc31) ).

cnf(clause2,negated_conjecture,
    event(skc30) ).

cnf(clause3,negated_conjecture,
    old(skc29) ).

cnf(clause4,negated_conjecture,
    street(skc28) ).

cnf(clause5,negated_conjecture,
    seat(skc27) ).

cnf(clause6,negated_conjecture,
    front(skc26) ).

cnf(clause7,negated_conjecture,
    fellow(skc25) ).

cnf(clause8,negated_conjecture,
    young(skc24) ).

cnf(clause9,negated_conjecture,
    city(skc23) ).

cnf(clause10,negated_conjecture,
    event(skc22) ).

cnf(clause11,negated_conjecture,
    old(skc21) ).

cnf(clause12,negated_conjecture,
    street(skc20) ).

cnf(clause13,negated_conjecture,
    front(skc19) ).

cnf(clause14,negated_conjecture,
    seat(skc18) ).

cnf(clause15,negated_conjecture,
    fellow(skc17) ).

cnf(clause16,negated_conjecture,
    young(skc16) ).

cnf(clause17,negated_conjecture,
    ( ssSkC0
    | lonely(skc28) ) ).

cnf(clause18,negated_conjecture,
    ( ssSkC0
    | way(skc28) ) ).

cnf(clause19,negated_conjecture,
    ( ssSkC0
    | chevy(skc29) ) ).

cnf(clause20,negated_conjecture,
    ( ssSkC0
    | car(skc29) ) ).

cnf(clause21,negated_conjecture,
    ( ssSkC0
    | white(skc29) ) ).

cnf(clause22,negated_conjecture,
    ( ssSkC0
    | dirty(skc29) ) ).

cnf(clause23,negated_conjecture,
    ( ssSkC0
    | hollywood(skc31) ) ).

cnf(clause24,negated_conjecture,
    ( ssSkC0
    | fellow(skc24) ) ).

cnf(clause25,negated_conjecture,
    ( ssSkC0
    | man(skc24) ) ).

cnf(clause26,negated_conjecture,
    ( ssSkC0
    | front(skc27) ) ).

cnf(clause27,negated_conjecture,
    ( ssSkC0
    | furniture(skc27) ) ).

cnf(clause28,negated_conjecture,
    ( ssSkC0
    | young(skc25) ) ).

cnf(clause29,negated_conjecture,
    ( ssSkC0
    | man(skc25) ) ).

cnf(clause30,negated_conjecture,
    ( ssSkC0
    | seat(skc26) ) ).

cnf(clause31,negated_conjecture,
    ( ssSkC0
    | furniture(skc26) ) ).

cnf(clause32,negated_conjecture,
    ( ~ ssSkC0
    | lonely(skc20) ) ).

cnf(clause33,negated_conjecture,
    ( ~ ssSkC0
    | way(skc20) ) ).

cnf(clause34,negated_conjecture,
    ( ~ ssSkC0
    | chevy(skc21) ) ).

cnf(clause35,negated_conjecture,
    ( ~ ssSkC0
    | car(skc21) ) ).

cnf(clause36,negated_conjecture,
    ( ~ ssSkC0
    | white(skc21) ) ).

cnf(clause37,negated_conjecture,
    ( ~ ssSkC0
    | dirty(skc21) ) ).

cnf(clause38,negated_conjecture,
    ( ~ ssSkC0
    | hollywood(skc23) ) ).

cnf(clause39,negated_conjecture,
    ( ~ ssSkC0
    | seat(skc19) ) ).

cnf(clause40,negated_conjecture,
    ( ~ ssSkC0
    | furniture(skc19) ) ).

cnf(clause41,negated_conjecture,
    ( ~ ssSkC0
    | fellow(skc16) ) ).

cnf(clause42,negated_conjecture,
    ( ~ ssSkC0
    | man(skc16) ) ).

cnf(clause43,negated_conjecture,
    ( ~ ssSkC0
    | front(skc18) ) ).

cnf(clause44,negated_conjecture,
    ( ~ ssSkC0
    | furniture(skc18) ) ).

cnf(clause45,negated_conjecture,
    ( ~ ssSkC0
    | young(skc17) ) ).

cnf(clause46,negated_conjecture,
    ( ~ ssSkC0
    | man(skc17) ) ).

cnf(clause47,negated_conjecture,
    ( ssSkC0
    | down(skc30,skc28) ) ).

cnf(clause48,negated_conjecture,
    ( ssSkC0
    | barrel(skc30,skc29) ) ).

cnf(clause49,negated_conjecture,
    ( ssSkC0
    | in(skc30,skc31) ) ).

cnf(clause50,negated_conjecture,
    ( ssSkC0
    | in(skc24,skc27) ) ).

cnf(clause51,negated_conjecture,
    ( ssSkC0
    | in(skc25,skc26) ) ).

cnf(clause52,negated_conjecture,
    ( ~ ssSkC0
    | down(skc22,skc20) ) ).

cnf(clause53,negated_conjecture,
    ( ~ ssSkC0
    | barrel(skc22,skc21) ) ).

cnf(clause54,negated_conjecture,
    ( ~ ssSkC0
    | in(skc22,skc23) ) ).

cnf(clause55,negated_conjecture,
    ( ~ ssSkC0
    | in(skc16,skc19) ) ).

cnf(clause56,negated_conjecture,
    ( ~ ssSkC0
    | in(skc17,skc18) ) ).

cnf(clause57,negated_conjecture,
    ( skc25 != skc24
    | ssSkC0 ) ).

cnf(clause58,negated_conjecture,
    ( skc17 != skc16
    | ~ ssSkC0 ) ).

cnf(clause59,negated_conjecture,
    ( ~ lonely(U)
    | ~ way(U)
    | ~ street(U)
    | ~ chevy(V)
    | ~ car(V)
    | ~ white(V)
    | ~ dirty(V)
    | ~ old(V)
    | ~ down(W,U)
    | ~ barrel(W,V)
    | ~ event(W)
    | ~ hollywood(X)
    | ~ city(X)
    | ~ in(W,X)
    | ~ seat(Y)
    | ~ furniture(Y)
    | ~ front(Y)
    | ~ in(Z,Y)
    | ~ fellow(Z)
    | ~ man(Z)
    | ~ young(Z)
    | ~ in(X1,X2)
    | ~ front(X2)
    | ~ furniture(X2)
    | ~ seat(X2)
    | ~ young(X1)
    | ~ man(X1)
    | ~ fellow(X1)
    | ssSkC0
    | X1 = Z ) ).

cnf(clause60,negated_conjecture,
    ( ~ lonely(U)
    | ~ way(U)
    | ~ street(U)
    | ~ chevy(V)
    | ~ car(V)
    | ~ white(V)
    | ~ dirty(V)
    | ~ old(V)
    | ~ down(W,U)
    | ~ barrel(W,V)
    | ~ event(W)
    | ~ hollywood(X)
    | ~ city(X)
    | ~ in(W,X)
    | ~ fellow(Y)
    | ~ man(Y)
    | ~ young(Y)
    | ~ in(Y,Z)
    | ~ front(Z)
    | ~ furniture(Z)
    | ~ seat(Z)
    | ~ young(X1)
    | ~ man(X1)
    | ~ fellow(X1)
    | ~ seat(X2)
    | ~ furniture(X2)
    | ~ front(X2)
    | ~ in(X1,X2)
    | ~ ssSkC0
    | X1 = Y ) ).

%--------------------------------------------------------------------------
