%--------------------------------------------------------------------------
% File     : NLP001-1 : TPTP v9.2.1. Released v2.4.0.
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".

% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner (1999), FTP'2000 - Problem Sets
% Source   : [TPTP]
% Names    :

% Status   : Unsatisfiable
% Rating   : 0.12 v9.1.0, 0.14 v9.0.0, 0.00 v2.4.0
% Syntax   : Number of clauses     :   30 (   8 unt;  10 nHn;  30 RR)
%            Number of literals    :   78 (   0 equ;  39 neg)
%            Maximal clause size   :   15 (   2 avg)
%            Maximal term depth    :    1 (   1 avg)
%            Number of predicates  :   15 (  15 usr;   1 prp; 0-2 aty)
%            Number of functors    :    8 (   8 usr;   8 con; 0-0 aty)
%            Number of variables   :    8 (   0 sgn)
% SPC      : CNF_UNS_EPR_NEQ_NHN

% Comments : Created from NLP0.p using FLOTTER
%--------------------------------------------------------------------------
cnf(clause1,negated_conjecture,
    hollywood(skc15) ).

cnf(clause2,negated_conjecture,
    event(skc14) ).

cnf(clause3,negated_conjecture,
    street(skc13) ).

cnf(clause4,negated_conjecture,
    old(skc12) ).

cnf(clause5,negated_conjecture,
    hollywood(skc11) ).

cnf(clause6,negated_conjecture,
    event(skc10) ).

cnf(clause7,negated_conjecture,
    chevy(skc9) ).

cnf(clause8,negated_conjecture,
    lonely(skc8) ).

cnf(clause9,negated_conjecture,
    ( ssSkC0
    | chevy(skc12) ) ).

cnf(clause10,negated_conjecture,
    ( ssSkC0
    | car(skc12) ) ).

cnf(clause11,negated_conjecture,
    ( ssSkC0
    | white(skc12) ) ).

cnf(clause12,negated_conjecture,
    ( ssSkC0
    | dirty(skc12) ) ).

cnf(clause13,negated_conjecture,
    ( ssSkC0
    | lonely(skc13) ) ).

cnf(clause14,negated_conjecture,
    ( ssSkC0
    | way(skc13) ) ).

cnf(clause15,negated_conjecture,
    ( ssSkC0
    | city(skc15) ) ).

cnf(clause16,negated_conjecture,
    ( ~ ssSkC0
    | street(skc8) ) ).

cnf(clause17,negated_conjecture,
    ( ~ ssSkC0
    | way(skc8) ) ).

cnf(clause18,negated_conjecture,
    ( ~ ssSkC0
    | old(skc9) ) ).

cnf(clause19,negated_conjecture,
    ( ~ ssSkC0
    | dirty(skc9) ) ).

cnf(clause20,negated_conjecture,
    ( ~ ssSkC0
    | white(skc9) ) ).

cnf(clause21,negated_conjecture,
    ( ~ ssSkC0
    | car(skc9) ) ).

cnf(clause22,negated_conjecture,
    ( ~ ssSkC0
    | city(skc11) ) ).

cnf(clause23,negated_conjecture,
    ( ssSkC0
    | barrel(skc14,skc12) ) ).

cnf(clause24,negated_conjecture,
    ( ssSkC0
    | down(skc14,skc13) ) ).

cnf(clause25,negated_conjecture,
    ( ssSkC0
    | in(skc14,skc15) ) ).

cnf(clause26,negated_conjecture,
    ( ~ ssSkC0
    | barrel(skc10,skc9) ) ).

cnf(clause27,negated_conjecture,
    ( ~ ssSkC0
    | down(skc10,skc8) ) ).

cnf(clause28,negated_conjecture,
    ( ~ ssSkC0
    | in(skc10,skc11) ) ).

cnf(clause29,negated_conjecture,
    ( ~ street(U)
    | ~ way(U)
    | ~ lonely(U)
    | ~ old(V)
    | ~ dirty(V)
    | ~ white(V)
    | ~ car(V)
    | ~ chevy(V)
    | ~ event(W)
    | ~ barrel(W,V)
    | ~ down(W,U)
    | ~ in(W,X)
    | ~ city(X)
    | ~ hollywood(X)
    | ssSkC0 ) ).

cnf(clause30,negated_conjecture,
    ( ~ chevy(U)
    | ~ car(U)
    | ~ white(U)
    | ~ dirty(U)
    | ~ old(U)
    | ~ lonely(V)
    | ~ way(V)
    | ~ street(V)
    | ~ event(W)
    | ~ barrel(W,U)
    | ~ down(W,V)
    | ~ in(W,X)
    | ~ city(X)
    | ~ hollywood(X)
    | ~ ssSkC0 ) ).

%--------------------------------------------------------------------------
