%--------------------------------------------------------------------------
% File     : TOP002-2 : TPTP v9.2.1. Released v1.0.0.
% Domain   : Topology
% Problem  : Topology generated by a basis forms a topological space, part 2
% Version  : [WM89] axioms : Incomplete > Reduced & Augmented > Incomplete.
% English  :

% Refs     : [WM89]  Wick & McCune (1989), Automated Reasoning about Elemen
% Source   : [WM89]
% Names    : Lemma 1b [WM89]

% Status   : Unsatisfiable
% Rating   : 0.00 v6.3.0, 0.14 v6.2.0, 0.00 v2.0.0
% Syntax   : Number of clauses     :    3 (   2 unt;   1 nHn;   2 RR)
%            Number of literals    :    4 (   0 equ;   2 neg)
%            Maximal clause size   :    2 (   1 avg)
%            Maximal term depth    :    2 (   1 avg)
%            Number of predicates  :    2 (   2 usr;   0 prp; 2-2 aty)
%            Number of functors    :    4 (   4 usr;   2 con; 0-2 aty)
%            Number of variables   :    3 (   1 sgn)
% SPC      : CNF_UNS_RFO_NEQ_NHN

% Comments : The axioms in this version are known to be incomplete. To
%            make them complete it is be necessary to add appropriate set
%            theory axioms.
%--------------------------------------------------------------------------
%----Include Point-set topology axioms
% include('Axioms/TOP001-0.ax').
%--------------------------------------------------------------------------
%----Topology generated by a basis
cnf(topology_generated_40,axiom,
    ( element_of_collection(U,top_of_basis(Vf))
    | element_of_set(f11(Vf,U),U) ) ).

cnf(set_theory_6,axiom,
    ~ element_of_set(X,empty_set) ).

%----Not used in the reduced version
% input_clause(lemma_1b_1,negated_conjecture,
%     [++basis(cx,f)]).

cnf(lemma_1b_2,negated_conjecture,
    ~ element_of_collection(empty_set,top_of_basis(f)) ).

%--------------------------------------------------------------------------
