%--------------------------------------------------------------------------
% File     : NLP005-1 : TPTP v9.2.1. Released v2.4.0.
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem 5
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".

% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner (1999), FTP'2000 - Problem Sets
% Source   : [TPTP]
% Names    :

% Status   : Satisfiable
% Rating   : 0.00 v2.6.0, 0.17 v2.5.0, 0.25 v2.4.0
% Syntax   : Number of clauses     :   57 (  15 unt;  19 nHn;  57 RR)
%            Number of literals    :  152 (   4 equ;  77 neg)
%            Maximal clause size   :   30 (   2 avg)
%            Maximal term depth    :    1 (   1 avg)
%            Number of predicates  :   22 (  21 usr;   1 prp; 0-2 aty)
%            Number of functors    :   15 (  15 usr;  15 con; 0-0 aty)
%            Number of variables   :   15 (   0 sgn)
% SPC      : CNF_SAT_EPR_EQU_NUE

% Comments : Created from NLP005+1.p using FLOTTER
%--------------------------------------------------------------------------
cnf(clause1,negated_conjecture,
    city(skc29) ).

cnf(clause2,negated_conjecture,
    event(skc28) ).

cnf(clause3,negated_conjecture,
    old(skc27) ).

cnf(clause4,negated_conjecture,
    street(skc26) ).

cnf(clause5,negated_conjecture,
    seat(skc25) ).

cnf(clause6,negated_conjecture,
    young(skc24) ).

cnf(clause7,negated_conjecture,
    fellow(skc23) ).

cnf(clause8,negated_conjecture,
    hollywood(skc22) ).

cnf(clause9,negated_conjecture,
    event(skc21) ).

cnf(clause10,negated_conjecture,
    street(skc20) ).

cnf(clause11,negated_conjecture,
    old(skc19) ).

cnf(clause12,negated_conjecture,
    front(skc18) ).

cnf(clause13,negated_conjecture,
    seat(skc17) ).

cnf(clause14,negated_conjecture,
    fellow(skc16) ).

cnf(clause15,negated_conjecture,
    young(skc15) ).

cnf(clause16,negated_conjecture,
    ( ssSkC0
    | lonely(skc26) ) ).

cnf(clause17,negated_conjecture,
    ( ssSkC0
    | way(skc26) ) ).

cnf(clause18,negated_conjecture,
    ( ssSkC0
    | chevy(skc27) ) ).

cnf(clause19,negated_conjecture,
    ( ssSkC0
    | car(skc27) ) ).

cnf(clause20,negated_conjecture,
    ( ssSkC0
    | white(skc27) ) ).

cnf(clause21,negated_conjecture,
    ( ssSkC0
    | dirty(skc27) ) ).

cnf(clause22,negated_conjecture,
    ( ssSkC0
    | hollywood(skc29) ) ).

cnf(clause23,negated_conjecture,
    ( ssSkC0
    | young(skc23) ) ).

cnf(clause24,negated_conjecture,
    ( ssSkC0
    | man(skc23) ) ).

cnf(clause25,negated_conjecture,
    ( ssSkC0
    | fellow(skc24) ) ).

cnf(clause26,negated_conjecture,
    ( ssSkC0
    | man(skc24) ) ).

cnf(clause27,negated_conjecture,
    ( ssSkC0
    | front(skc25) ) ).

cnf(clause28,negated_conjecture,
    ( ssSkC0
    | furniture(skc25) ) ).

cnf(clause29,negated_conjecture,
    ( ~ ssSkC0
    | chevy(skc19) ) ).

cnf(clause30,negated_conjecture,
    ( ~ ssSkC0
    | car(skc19) ) ).

cnf(clause31,negated_conjecture,
    ( ~ ssSkC0
    | white(skc19) ) ).

cnf(clause32,negated_conjecture,
    ( ~ ssSkC0
    | dirty(skc19) ) ).

cnf(clause33,negated_conjecture,
    ( ~ ssSkC0
    | lonely(skc20) ) ).

cnf(clause34,negated_conjecture,
    ( ~ ssSkC0
    | way(skc20) ) ).

cnf(clause35,negated_conjecture,
    ( ~ ssSkC0
    | city(skc22) ) ).

cnf(clause36,negated_conjecture,
    ( ~ ssSkC0
    | seat(skc18) ) ).

cnf(clause37,negated_conjecture,
    ( ~ ssSkC0
    | furniture(skc18) ) ).

cnf(clause38,negated_conjecture,
    ( ~ ssSkC0
    | fellow(skc15) ) ).

cnf(clause39,negated_conjecture,
    ( ~ ssSkC0
    | man(skc15) ) ).

cnf(clause40,negated_conjecture,
    ( ~ ssSkC0
    | front(skc17) ) ).

cnf(clause41,negated_conjecture,
    ( ~ ssSkC0
    | furniture(skc17) ) ).

cnf(clause42,negated_conjecture,
    ( ~ ssSkC0
    | young(skc16) ) ).

cnf(clause43,negated_conjecture,
    ( ~ ssSkC0
    | man(skc16) ) ).

cnf(clause44,negated_conjecture,
    ( ssSkC0
    | down(skc28,skc26) ) ).

cnf(clause45,negated_conjecture,
    ( ssSkC0
    | barrel(skc28,skc27) ) ).

cnf(clause46,negated_conjecture,
    ( ssSkC0
    | in(skc28,skc29) ) ).

cnf(clause47,negated_conjecture,
    ( ssSkC0
    | in(skc23,skc25) ) ).

cnf(clause48,negated_conjecture,
    ( ssSkC0
    | in(skc24,skc25) ) ).

cnf(clause49,negated_conjecture,
    ( ~ ssSkC0
    | barrel(skc21,skc19) ) ).

cnf(clause50,negated_conjecture,
    ( ~ ssSkC0
    | down(skc21,skc20) ) ).

cnf(clause51,negated_conjecture,
    ( ~ ssSkC0
    | in(skc21,skc22) ) ).

cnf(clause52,negated_conjecture,
    ( ~ ssSkC0
    | in(skc15,skc18) ) ).

cnf(clause53,negated_conjecture,
    ( ~ ssSkC0
    | in(skc16,skc17) ) ).

cnf(clause54,negated_conjecture,
    ( skc24 != skc23
    | ssSkC0 ) ).

cnf(clause55,negated_conjecture,
    ( skc16 != skc15
    | ~ ssSkC0 ) ).

cnf(clause56,negated_conjecture,
    ( ~ lonely(U)
    | ~ way(U)
    | ~ street(U)
    | ~ chevy(V)
    | ~ car(V)
    | ~ white(V)
    | ~ dirty(V)
    | ~ old(V)
    | ~ down(W,U)
    | ~ barrel(W,V)
    | ~ event(W)
    | ~ hollywood(X)
    | ~ city(X)
    | ~ in(W,X)
    | ~ young(Y)
    | ~ man(Y)
    | ~ fellow(Y)
    | ~ fellow(Z)
    | ~ man(Z)
    | ~ young(Z)
    | ~ in(Y,X1)
    | ~ in(Z,X1)
    | ~ front(X1)
    | ~ furniture(X1)
    | ~ seat(X1)
    | ~ ssSkC0
    | Z = Y ) ).

cnf(clause57,negated_conjecture,
    ( ~ chevy(U)
    | ~ car(U)
    | ~ white(U)
    | ~ dirty(U)
    | ~ old(U)
    | ~ lonely(V)
    | ~ way(V)
    | ~ street(V)
    | ~ event(W)
    | ~ barrel(W,U)
    | ~ down(W,V)
    | ~ in(W,X)
    | ~ city(X)
    | ~ hollywood(X)
    | ~ seat(Y)
    | ~ furniture(Y)
    | ~ front(Y)
    | ~ in(Z,Y)
    | ~ fellow(Z)
    | ~ man(Z)
    | ~ young(Z)
    | ~ in(X1,X2)
    | ~ front(X2)
    | ~ furniture(X2)
    | ~ seat(X2)
    | ~ young(X1)
    | ~ man(X1)
    | ~ fellow(X1)
    | ssSkC0
    | X1 = Z ) ).

%--------------------------------------------------------------------------
